version: 2.0.{build}

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

before_build:
  - nuget restore gui/OptickApp_vs2017.sln
  
build_script:
  - tools\Windows\premake5.exe vs2015
  - cd build/vs2015
  - MsBuild Optick.sln /t:Rebuild /p:Configuration=%CONFIGURATION%
  - cd ../../gui
  - MsBuild OptickApp_vs2017.sln /t:Rebuild /p:Configuration=%CONFIGURATION%